package_name: openscad
version: 0.0.1dev
license: GPLv3+ and GPLv2 with exceptions
authors: [Miro Hrončok <miro@hroncok.cz>, Marek Žehra <marek@zehra.cz>]
homepage: https://github.com/3DprintFIT/dap-openscad
summary: Create 3D printing projects for OpenSCAD
bugreports: https://github.com/3DprintFIT/dap-openscad/issues
description: |
    This assistants helps you to create new OpenSCAD project for 3D printing.
    We use it in our 3D printing lab to store our 3D printers on Github.
    
    Projects created with this assistant have a `Makefile` to build the 3D models form OpenSCAD sources.
    To do so, run `make`. You can also generate the images by `make images` or print plates with `make arrange`.
    Observe the generated `Makefile` to see all available options.
